Repository TeamCovertDragon/Harbinger, pull requests merged in 2019-06, with the labels that each got.

#23 fix(ch. 4):texture->textures
  chapter-04/index.md
Labels: Type: Errata

#24 fix(ch. 21): provide precise criteria on Ingredient.isSimple()
  chapter-21/forge-extension/ingredient-factory.md
Labels: Status: Help Wanted, Type: Errata

#27 Clean up demonstration usage of `SimpleNetworkWrapper`
  chapter-07/forge-extension/simple-network-wrapper.md
Labels: Status: Work In Progress, Type: Errata

#28 Extra clarification for #27
  chapter-07/forge-extension/simple-network-wrapper.md
Labels: Status: Work In Progress, Type: Errata

#29 fix(ch. 13): correct a typo
  chapter-13/note.md
Labels: Status: Pending, Type: Errata
