Repository TeamCovertDragon/Harbinger, pull requests merged in 2019-11, with the labels that each got.

#52 fix(ch. 01): correct file name
  chapter-01/forgegradle.md
Labels: Solution: Merged, Status: Finalized, Type: Errata

#55 解释Container与GuiContainer的关系图部分，描述与ustc-zzzz的教程不符
  chapter-14/index.md
Labels: Status: Pending, Type: Errata

#56 Fix wrong method parameters in Dimension registry
  chapter-19/dimension/index.md
Labels: Status: Work In Progress, Type: Errata

#53 Rewrite TileEntity and Capability articles
  SUMMARY.md
  chapter-04/enchantment.md
  chapter-09/examples/index.md
  chapter-09/examples/inventory.md
  chapter-09/index.md
  chapter-09/ticking.md
  chapter-10/attach-cap.md
  chapter-10/index.md
  chapter-10/item-cap.md
  chapter-10/new-cap.md
  chapter-10/persistence.md
  chapter-11/forge-extension/animation.md
  chapter-27/container/block.md
  chapter-27/container/index.md
  chapter-27/container/item.md
  chapter-28/built-in/animation.md
  chapter-28/built-in/energy.md
  chapter-28/built-in/fluid.md
  chapter-28/built-in/index.md
  chapter-28/built-in/item.md
  chapter-28/index.md
  chapter-28/persistence.md
Labels: Status: Work In Progress, Type: Enhancement, Type: New Content
