Repository TeamCovertDragon/Harbinger, pull requests merged in 2019-10, with the labels that each got.

#44 fix(ch. 11): fix an intralink
  chapter-11/baked/custom-mesh.md
Labels: Status: Work In Progress, Type: Errata

#47 feat(ch. 19): `WorldType` explained
  chapter-19/dimension/type.md
Labels: Status: Work In Progress, Type: New Content

#48 fix(ch. 13, ch. 24): fix wrong package/class name
  chapter-13/index.md
  chapter-24/index.md
Labels: Status: Work In Progress, Type: Errata

#50 fix(ch. 5): correct example_block_model.json
  chapter-05/index.md
Labels: Status: Pending, Type: Errata

#51 fix(ch. 02): correct Gradle build success information
  chapter-02/index.md
Labels: Type: Errata
