Repository TeamCovertDragon/Harbinger, pull requests merged in 2019-05, with the labels that each got.

#8 feat(ch. 13): more information about i18n.
  chapter-13/index.md
Labels: Status: Considering, Type: New Content

#9 feat(ch. 13): change java properties link
  chapter-13/index.md
Labels: Status: Considering, Type: Enhancement

#12 修复#11
  book-pdf.json
  book.json
Labels: Type: Enhancement

#14 fix(ch. 21): fix example fault
  chapter-21/forge-extension/recipe-factory.md
Labels: Status: Work In Progress, Type: Errata

#15 feat(ch. 26): mention the i18n mechanics of config gui
  chapter-26/config-gui.md
  chapter-26/index.md
  chapter-27/container/block.md
Labels: Status: Work In Progress, Type: New Content
