Repository TeamCovertDragon/Harbinger, pull requests merged in 2020-01, with the labels that each got.

#60 fix(ch.26): display configElements directly in gui
  chapter-26/config-gui.md
Labels: Status: Considering, Type: Enhancement

#61 修正拼写错误
  chapter-20/villager-profession.md
Labels: Status: Reviewing, Type: Errata

#62 feat(readme): notice regarding new version
  README.md
Labels: Status: Reviewing, Type: Meta
